"use client";

import React, { useState, useEffect } from "react";
import { useAuth } from "@/lib/authContext";
import { db } from "@/lib/firebase";
import { collection, getDocs, doc, getDoc, query, where } from "firebase/firestore";
import Link from "next/link";
import { Search, Play, RotateCcw, Video, HelpCircle } from "lucide-react";

interface Lesson {
  videoId: string;
  title: string;
  quizGeneratedAt: any;
  qCount: number;
  status: "not_taken" | "pass" | "fail";
  highestScore: number;
  highestPct: number;
}

export default function LessonsCatalog() {
  const { user } = useAuth();
  const [lessons, setLessons] = useState<Lesson[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");

  useEffect(() => {
    async function loadCatalog() {
      if (!user) return;
      try {
        // 1. Fetch all generated videos on the platform
        const videosSnap = await getDocs(collection(db, "videos"));
        const videosList = videosSnap.docs.map((d) => d.data());

        // 2. Fetch user's attempts to map pass/fail status
        const attemptsRef = collection(db, "attempts");
        const q = query(attemptsRef, where("userId", "==", user.uid));
        const attemptsSnap = await getDocs(q);
        const attemptsList = attemptsSnap.docs.map((d) => d.data());

        // 3. Enrich catalog entries concurrently
        const enriched: Lesson[] = await Promise.all(
          videosList.map(async (v: any) => {
            let qCount = 8;
            try {
              const quizSnap = await getDoc(doc(db, "quizzes", v.videoId));
              if (quizSnap.exists()) {
                qCount = quizSnap.data().questions?.length || 8;
              }
            } catch (err) {
              console.error("Failed to load quiz details for counting:", err);
            }

            const videoAttempts = attemptsList.filter((a) => a.videoId === v.videoId);
            let status: "not_taken" | "pass" | "fail" = "not_taken";
            let highestScore = 0;
            let highestPct = 0;

            if (videoAttempts.length > 0) {
              videoAttempts.forEach((a) => {
                const totalAnswers = a.answers?.length || 0;
                const pct = totalAnswers > 0 ? a.score / totalAnswers : 0;
                if (pct > highestPct) {
                  highestPct = pct;
                  highestScore = a.score;
                }
              });
              status = highestPct >= 0.8 ? "pass" : "fail";
            }

            return {
              videoId: v.videoId,
              title: v.title || "YouTube Lesson",
              quizGeneratedAt: v.quizGeneratedAt,
              qCount,
              status,
              highestScore,
              highestPct: Math.round(highestPct * 100),
            };
          })
        );

        setLessons(enriched);
      } catch (err) {
        console.error("Error loading lessons catalog:", err);
      } finally {
        setLoading(false);
      }
    }

    loadCatalog();
  }, [user]);

  // Search filter matching titles
  const filteredLessons = lessons.filter((l) =>
    l.title.toLowerCase().includes(searchQuery.toLowerCase())
  );

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-24 gap-4">
        <svg className="animate-spin h-6 w-6 text-indigo-650" fill="none" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
        </svg>
        <span className="text-slate-400 text-[10px] font-bold uppercase tracking-wider">Retrieving lessons catalog...</span>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-display font-black text-slate-900 mb-1">Lessons Catalog</h1>
          <p className="text-xs text-slate-500 font-semibold leading-relaxed">
            Browse and take quizzes generated by all users on the platform.
          </p>
        </div>
        <Link
          href="/dashboard/generate"
          className="self-start md:self-auto px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs rounded-full transition-all shadow-sm hover:shadow uppercase tracking-wider cursor-pointer"
        >
          + Generate New Quiz
        </Link>
      </div>

      {/* Search Bar */}
      <div className="max-w-md relative flex items-center">
        <Search className="w-4 h-4 text-slate-450 absolute left-4" />
        <input
          type="text"
          placeholder="Search lessons by title..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full pl-11 pr-4 py-3 bg-white border border-slate-200/80 rounded-full text-xs placeholder:text-slate-400 focus:outline-none focus:border-indigo-500/50 text-slate-800 transition-all shadow-sm font-semibold"
        />
      </div>

      {/* Grid of Lesson Cards */}
      {filteredLessons.length === 0 ? (
        <div className="p-12 border border-slate-200/60 bg-white rounded-3xl text-center text-slate-400 text-xs shadow-sm">
          No lessons found matching your criteria. Try generating a new one!
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredLessons.map((lesson) => {
            return (
              <div
                key={lesson.videoId}
                className="bg-white border border-slate-200/60 hover:border-slate-350 transition-all duration-300 rounded-3xl overflow-hidden flex flex-col justify-between shadow-sm hover:shadow-md hover:-translate-y-0.5 group"
              >
                {/* Thumbnail Header */}
                <div className="relative aspect-video bg-slate-900 overflow-hidden shrink-0 border-b border-slate-100">
                  <img
                    src={`https://i.ytimg.com/vi/${lesson.videoId}/mqdefault.jpg`}
                    alt={lesson.title}
                    className="w-full h-full object-cover group-hover:scale-102 transition-all duration-500"
                    loading="lazy"
                    onError={(e) => {
                      (e.target as HTMLImageElement).src =
                        "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100' height='60' viewBox='0 0 100 60'%3E%3Crect width='100' height='60' fill='%23f1f5f9'/%3E%3Ctext x='50' y='35' font-family='sans-serif' font-size='10' fill='%2394a3b8' text-anchor='middle'%3EStudyMate%3C/text%3E%3C/svg%3E";
                    }}
                  />
                  {/* Status Pill Badge (No emojis) */}
                  <div className="absolute top-3 right-3">
                    {lesson.status === "pass" && (
                      <span className="px-2.5 py-0.5 rounded-full text-[9px] font-bold bg-white/95 border border-emerald-200 text-emerald-600 shadow-sm">
                        PASS ({lesson.highestPct}%)
                      </span>
                    )}
                    {lesson.status === "fail" && (
                      <span className="px-2.5 py-0.5 rounded-full text-[9px] font-bold bg-white/95 border border-rose-200 text-rose-600 shadow-sm">
                        FAIL ({lesson.highestPct}%)
                      </span>
                    )}
                    {lesson.status === "not_taken" && (
                      <span className="px-2.5 py-0.5 rounded-full text-[9px] font-bold bg-white/95 border border-slate-200 text-slate-500 shadow-sm">
                        NOT TAKEN
                      </span>
                    )}
                  </div>
                </div>

                {/* Info Content */}
                <div className="p-5 flex-grow flex flex-col justify-between">
                  <div className="space-y-2 mb-6">
                    <h3 className="font-bold text-slate-800 text-xs leading-snug line-clamp-2 min-h-[36px] group-hover:text-indigo-650 transition-colors">
                      {lesson.title}
                    </h3>
                    <div className="text-[9px] font-bold uppercase tracking-wider text-slate-400 flex flex-wrap items-center gap-1.5 font-semibold">
                      <span className="flex items-center gap-1">
                        <Video className="w-3 h-3 text-slate-400" />
                        <span>{lesson.videoId}</span>
                      </span>
                      <span>•</span>
                      <span className="flex items-center gap-1">
                        <HelpCircle className="w-3 h-3 text-slate-400" />
                        <span>{lesson.qCount} Questions</span>
                      </span>
                    </div>
                  </div>

                  {/* Actions buttons (fully rounded) */}
                  <div className="flex items-center justify-between gap-3 border-t border-slate-100 pt-4">
                    {lesson.status !== "not_taken" ? (
                      <>
                        <Link
                          href={`/quiz/${lesson.videoId}/results`}
                          className="text-xs font-bold text-slate-400 hover:text-slate-700 transition-colors uppercase tracking-wider text-[10px]"
                        >
                          Review Scores
                        </Link>
                        <Link
                          href={`/quiz/${lesson.videoId}`}
                          className="px-4 py-2 bg-slate-50 hover:bg-slate-100 text-slate-700 text-[10px] font-bold rounded-full transition-all border border-slate-200 flex items-center gap-1.5 cursor-pointer uppercase tracking-wider"
                        >
                          <RotateCcw className="w-3 h-3" />
                          <span>Retake</span>
                        </Link>
                      </>
                    ) : (
                      <>
                        <div className="w-1" />
                        <Link
                          href={`/quiz/${lesson.videoId}`}
                          className="px-5 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-[10px] font-bold rounded-full transition-all shadow-sm hover:shadow flex items-center gap-1.5 cursor-pointer uppercase tracking-wider"
                        >
                          <Play className="w-3 h-3 fill-current" />
                          <span>Take Quiz</span>
                        </Link>
                      </>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
